version: '3.8'

services:
  sdn_network:
    build:
      context: ../
      dockerfile: docker/mininet.Dockerfile
    container_name: ddos_sdn_sim
    privileged: true # REQUIRED for Mininet to create virtual interfaces and namespaces
    network_mode: "host" # Allows Ryu to bind to host ports if needed, and Mininet to work easily
    volumes:
      - ../src/sdn_controller:/app/sdn_controller
      - ../scripts:/app/scripts
    # Run the Ryu controller in the background, then launch the Mininet topology
    command: >
      bash -c "ryu-manager sdn_controller/ryu_app.py --wsapi-port 8080 & 
      sleep 3 && 
      python3 sdn_controller/mininet_topo.py"
